version: 0.0
os: linux
files:
  - source: Config/config.txt
    destination: /webapps/Config
  - source: source
    destination: /webapps/myApp
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600