version: 0.0
os: linux
files:
  - source: src
    destination: /webapps/4chat
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600